export const CONFIG = {
  ticksPerDay: 20,
  startDateIso: '2026-01-01',
  startingCredits: 1000,
  taxPerMillionPerDay: 1,
  squadron: {
    attack: 6,
    shotsPerTick: 1,
    hp: 100,
    armor: 2,
    speedKmPerDay: 24000,
    baseCost: 500,
    costGrowth: 0.5,
  },
  ufoAbductor: {
    attack: 4,
    shotsPerTick: 1,
    hp: 60,
    armor: 1,
    speedKmPerDay: 8000,
    descentKm: 2000,
    abductionPerDay: 10,
    abductionDays: 1,
  },
  waves: {
    firstWaveDayMin: 10,
    firstWaveDayMax: 15,
    intervalBaseDays: 14,
    intervalShrinkPerWave: 1,
    intervalMinDays: 5,
    ufosBase: 1,
    ufosPerWave: 1,
    victoryWaves: 10,
  },
  saveVersion: 1,
} as const;
